/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "tema1.h"
#include "token.h"

extern approval *all_approvals;
extern user_in_db *db_users;
extern char **users, **resources;
extern int no_users, no_resources, token_valability, no_approvals, crt_approval;

request_authorization *
request_authorization_1_svc(char *arg1,  struct svc_req *rqstp)
{
	static request_authorization result;
	result.status = 1;
	result.request_token = " ";
	for (int i = 0; i < no_users; i++) {
		if (strncmp(users[i], arg1, strlen(arg1)) == 0) {
			result.status = 0;
			result.request_token = generate_access_token(arg1);
			break;
		}
	}
	//printf("ai iesi din autho\n");
	return &result;
}

token *
approve_request_token_1_svc(char *arg1,  struct svc_req *rqstp)
{
    // for (int i = 0; i < no_approvals; i++) {
    //     for (int j = 0; j < all_approvals[i].no_permissions; j++) {
    //         printf("%s %s\n", all_approvals[i].list_permissions.list_permissions_val[j].file, all_approvals[i].list_permissions.list_permissions_val[j].permission);
    //     }
    // }

    static token result;
    result.crt_permissions = crt_approval;
    result.is_automatic_refreshed = 0;
    result.is_signed = 0;
    result.ttl = 0;
    
    // Allocate memory for token_value
    result.token_value = (char *)malloc((SIZE_USER_ID + 1) * sizeof(char));
	if (!result.token_value) {
		printf("Allocation failed\n");
		exit(1);
	}

    memcpy(result.token_value, arg1, SIZE_USER_ID);

    printf("permisiuni date %d\n", all_approvals[crt_approval].no_permissions);

    if (strcmp(all_approvals[crt_approval].list_permissions.list_permissions_val->file, "*") == 0) {
        if (strcmp(all_approvals[crt_approval].list_permissions.list_permissions_val->permission, "-") == 0) {
            result.is_signed = 0;
        }
    } else {
        result.is_signed = 1;
    }
	crt_approval++;

    //printf("nr_crt_approval %d\n", crt_approval);

    return &result;
}

request_access_token *
request_access_token_1_svc(request_access_token_params arg1,  struct svc_req *rqstp)
{
	static request_access_token  result;
	printf("%d\n", arg1.user_token.is_signed);
	printf("aici acum\n");
	result.access_token = " ";
	result.refresh_token = " ";
	result.request_token = " ";
	result.status = 0;
	if (arg1.user_token.is_signed == 1) {
		result.access_token = generate_access_token(arg1.user_token.token_value);
		if (arg1.user_token.is_automatic_refreshed == 1) {
			result.refresh_token = generate_access_token(result.access_token);
		}
		result.request_token = arg1.user_token.token_value;
		result.status = 1;
		for (int i = 0; i < no_users; i++) {
			//if (strcmp(db_users[i].user_id, arg1.id) == 0 ) {
				//db_users[i].user_token.crt_permissions = arg1.user_token.crt_permissions;
				//db_users[i].user_token.is_automatic_refreshed = arg1.user_token.is_automatic_refreshed;
				//db_users[i].user_token.is_signed = arg1.user_token.is_signed;
				//memcpy(db_users[i].user_token.token_value, arg1.user_token.token_value, SIZE_USER_ID);
				//db_users[i].user_token.ttl = arg1.user_token.ttl;
				//break;
			//}
		}
		if (arg1.user_token.is_automatic_refreshed == 0) {
			printf("BEGIN %s AUTHZ\n", arg1.id);
			printf("  RequestToken = %s\n", result.request_token);
			printf("  AccessToken = %s\n", result.access_token);
		} else {
			printf("BEGIN %s AUTHZ\n", arg1.id);
			printf("  RequestToken = %s\n", result.request_token);
			printf("  AccessToken = %s\n", result.access_token);
			printf("  RefreshToken = %s\n", result.refresh_token);	
		}
	}

	return &result;
}

int *
validate_delegated_action_1_svc(validate_action_params arg1,  struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}