/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEMA1_H_RPCGEN
#define _TEMA1_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define LINESIZE 50
#define SIZE_USER_ID 15
#define SIZE_RESOURCE_NAME 20
#define SIZE_PERMISSION 10

struct token {
	char *token_value;
	char *refresh_token;
	int ttl;
	int is_signed;
	int crt_permissions;
	int is_automatic_refreshed;
};
typedef struct token token;

struct file_permission {
	char *file;
	char *permission;
};
typedef struct file_permission file_permission;

struct approval {
	struct {
		u_int list_permissions_len;
		file_permission *list_permissions_val;
	} list_permissions;
	int no_permissions;
};
typedef struct approval approval;

struct user_in_db {
	char *user_id;
	token user_token;
};
typedef struct user_in_db user_in_db;

struct request_authorization {
	int status;
	char *request_token;
};
typedef struct request_authorization request_authorization;

struct request_access_token_params {
	char *id;
	token user_token;
};
typedef struct request_access_token_params request_access_token_params;

struct request_access_token {
	char *request_token;
	char *access_token;
	char *refresh_token;
	int status;
};
typedef struct request_access_token request_access_token;

struct validate_action_params {
	char *operation;
	char *resource;
	char *user_id;
};
typedef struct validate_action_params validate_action_params;

#define TEMA1_PROG 0x3123457
#define TEMA1_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define REQUEST_AUTHORIZATION 1
extern  request_authorization * request_authorization_1(char *, CLIENT *);
extern  request_authorization * request_authorization_1_svc(char *, struct svc_req *);
#define APPROVE_REQUEST_TOKEN 2
extern  token * approve_request_token_1(char *, CLIENT *);
extern  token * approve_request_token_1_svc(char *, struct svc_req *);
#define REQUEST_ACCESS_TOKEN 3
extern  request_access_token * request_access_token_1(request_access_token_params , CLIENT *);
extern  request_access_token * request_access_token_1_svc(request_access_token_params , struct svc_req *);
#define VALIDATE_DELEGATED_ACTION 4
extern  int * validate_delegated_action_1(validate_action_params , CLIENT *);
extern  int * validate_delegated_action_1_svc(validate_action_params , struct svc_req *);
extern int tema1_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define REQUEST_AUTHORIZATION 1
extern  request_authorization * request_authorization_1();
extern  request_authorization * request_authorization_1_svc();
#define APPROVE_REQUEST_TOKEN 2
extern  token * approve_request_token_1();
extern  token * approve_request_token_1_svc();
#define REQUEST_ACCESS_TOKEN 3
extern  request_access_token * request_access_token_1();
extern  request_access_token * request_access_token_1_svc();
#define VALIDATE_DELEGATED_ACTION 4
extern  int * validate_delegated_action_1();
extern  int * validate_delegated_action_1_svc();
extern int tema1_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_token (XDR *, token*);
extern  bool_t xdr_file_permission (XDR *, file_permission*);
extern  bool_t xdr_approval (XDR *, approval*);
extern  bool_t xdr_user_in_db (XDR *, user_in_db*);
extern  bool_t xdr_request_authorization (XDR *, request_authorization*);
extern  bool_t xdr_request_access_token_params (XDR *, request_access_token_params*);
extern  bool_t xdr_request_access_token (XDR *, request_access_token*);
extern  bool_t xdr_validate_action_params (XDR *, validate_action_params*);

#else /* K&R C */
extern bool_t xdr_token ();
extern bool_t xdr_file_permission ();
extern bool_t xdr_approval ();
extern bool_t xdr_user_in_db ();
extern bool_t xdr_request_authorization ();
extern bool_t xdr_request_access_token_params ();
extern bool_t xdr_request_access_token ();
extern bool_t xdr_validate_action_params ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEMA1_H_RPCGEN */
