/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "tema1.h"

char buf[LINESIZE];

void
tema1_prog_1(char *host, char *filename_operations)
{
	CLIENT *clnt;

#ifndef	DEBUG
	clnt = clnt_create (host, TEMA1_PROG, TEMA1_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	FILE *file = fopen(filename_operations, "r");
	if (file == NULL) {
		printf("Cannot open %s\n", filename_operations);
		exit(1);
	}

	char *user_id, *operation, *type;

	while (fgets(buf, LINESIZE, file)) {
		user_id = strtok(buf, ",");
		operation = strtok(NULL, ",");
		type = strtok(NULL, ",");

		if (strcmp(operation, "REQUEST") == 0) {
			int automated_refresh = atoi(type);
			printf("request %d; user %s\n", automated_refresh, user_id);
			request_authorization *req_a =  request_authorization_1(user_id, clnt);

			if (req_a->status == 1) {
				printf("USER_NOT_FOUND\n");
			} else {
				printf("USER_FOUND");
			}
			
		} else {
			
		}
	}
	fclose(file);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host, *filename_operations;
	host = "localhost";

	if (argc < 2) {
		printf ("usage: %s fisier_operatii\n", argv[0]);
		exit (1);
	}
	filename_operations = argv[1];

	tema1_prog_1 (host, filename_operations);
exit (0);
}