/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "tema1.h"

char buf[LINESIZE];

void
tema1_prog_1(char *host, char *filename_operations)
{
	CLIENT *clnt;
	request_authorization  *result_1;
	char *request_authorization_1_arg1;
	approve_request_token  *result_2;
	char *approve_request_token_1_arg1;
	request_access_token  *result_3;
	request_access_token_params request_access_token_1_arg1;
	int  *result_4;
	validate_action_params validate_delegated_action_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, TEMA1_PROG, TEMA1_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	FILE *file = fopen(filename_operations, "r");
	if (file == NULL) {
		printf("Cannot open %s\n", filename_operations);
		exit(1);
	}

	char *user_id, *operation, *type;

	while (fgets(buf, LINESIZE, file)) {
		user_id = strtok(buf, ",");
		operation = strtok(NULL, ",");
		type = strtok(NULL, ",");

		if (strcmp(operation, "REQUEST") == 0) {
			int automated_refresh = atoi(type);
			printf("request %d\n", automated_refresh);
			
		} else {
			
		}
	}
	fclose(file);

	// result_1 = request_authorization_1(request_authorization_1_arg1, clnt);
	// if (result_1 == (request_authorization *) NULL) {
	// 	clnt_perror (clnt, "call failed");
	// }
	// result_2 = approve_request_token_1(approve_request_token_1_arg1, clnt);
	// if (result_2 == (approve_request_token *) NULL) {
	// 	clnt_perror (clnt, "call failed");
	// }
	// result_3 = request_access_token_1(request_access_token_1_arg1, clnt);
	// if (result_3 == (request_access_token *) NULL) {
	// 	clnt_perror (clnt, "call failed");
	// }
	// result_4 = validate_delegated_action_1(validate_delegated_action_1_arg1, clnt);
	// if (result_4 == (int *) NULL) {
	// 	clnt_perror (clnt, "call failed");
	// }
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host, *filename_operations;
	host = "localhost";

	if (argc < 2) {
		printf ("usage: %s fisier_operatii\n", argv[0]);
		exit (1);
	}
	filename_operations = argv[1];

	tema1_prog_1 (host, filename_operations);
exit (0);
}