/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "tema1.h"

request_authorization *
request_authorization_1_svc(char *arg1,  struct svc_req *rqstp)
{
	static request_authorization  result;

	/*
	 * insert server code here
	 */

	return &result;
}

approve_request_token *
approve_request_token_1_svc(char *arg1,  struct svc_req *rqstp)
{
	static approve_request_token  result;

	/*
	 * insert server code here
	 */

	return &result;
}

request_access_token *
request_access_token_1_svc(request_access_token_params arg1,  struct svc_req *rqstp)
{
	static request_access_token  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
validate_delegated_action_1_svc(validate_action_params arg1,  struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
